### ISSUE TITLE
Scripts fail for Xiaomi firmware images

### ISSUE THREAD

**Issue by ernstleierzopf** [jmariasantosdekra/MAS-Preloaded-Apps-Scripts#1]
we noticed that there were no results stored for Xiaomi images sourced from https://new.c.mi.com/global/miuidownload/index
It happens to all of the images we tested until now.

Following I send you the stack trace:
```
INFO  - done
Scanning app: com.google.android.marvin.talkback
APP com.google.android.marvin.talkback scanned before.
The results of the com.google.android.marvin.talkback app were obtained from App Defence Aliance.
mkdir: cannot create directory '/usr/src/app/android/': File exists
mkdir: cannot create directory '/usr/src/app/android/': File exists
Traceback (most recent call last):
  File "/usr/src/app/utils/collect_data.py", line 177, in <module>
    collect_data_script(uuid_execution)
  File "/usr/src/app/utils/collect_data.py", line 77, in collect_data_script
    value = formula.calculate_formula(0.01, 0.01, tests_list, uuid_execution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./utils/formula.py", line 82, in calculate_formula
    M = get_m_value(p, tests, uuid_execution)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./utils/formula.py", line 53, in get_m_value
    total_fails += r[i]
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
Analysis successfully executed
[+] Ran the Dekra script 
```

**Comment by ernstleierzopf** [comment]
proposed fix:
check if the permission exists in the configs (i.e. r[i] is not None) before adding to the total_fails and other variables.

**Comment by frandelpinodekra** [comment]
Hello Ernst,

This issue has been resolved in the latest version of the script uploaded today. This problem didn't occur because of any permission issue in config file, it was because a Python file was being launched as a process and we were taking what it displayed as the output. However, in some cases, an exception was thrown, so the expected value by the test case was an integer, but it captured the exception instead. This has been fixed, and now even though the exception is displayed on the screen, the expected value (an integer) is returned as a parameter. Due to this error, both the verdict value for this test case in the Report table and the matches found value in the Total_Fail_Counts table were NULL, due to to this exception.

Check it and we will close the issue.

**Comment by ernstleierzopf** [comment]
Quickly tested it with one image and the fix seems to work, thanks.
